/**
 * YouTube Extractor
 *
 * Specialized extractor for YouTube videos.
 * Features:
 * - YouTube video ID extraction from various URL formats
 * - Transcript extraction with language preferences
 * - Metadata extraction (title, description, duration, channel)
 * - Fallback to metadata only if transcript fails
 * - Support for auto-generated transcripts
 */

import type {
	ExtractionInput,
	ExtractionResult,
	YouTubeExtractor as IYouTubeExtractor,
	YouTubeMetadata,
	YouTubeOptions,
} from "../interfaces"
import { fetchYouTubeTranscriptFallback } from "../markitdown"

// ============================================================================
// Helper Functions
// ============================================================================

/**
 * Fetch video title using YouTube oEmbed API (free, no auth required)
 */
async function fetchTitleFromOEmbed(videoId: string): Promise<string | null> {
	try {
		const url = `https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=${videoId}&format=json`
		const response = await fetch(url, { signal: AbortSignal.timeout(5000) })
		if (!response.ok) return null
		const data = await response.json()
		return data.title || null
	} catch {
		return null
	}
}

// ============================================================================
// YouTube Extractor Implementation
// ============================================================================

/**
 * Extractor for YouTube videos
 */
export class YouTubeExtractor implements IYouTubeExtractor {
	readonly serviceName = "YouTubeExtractor"
	private initialized = false
	private readonly preferredLanguages: string[]

	constructor(preferredLanguages?: string[]) {
		this.preferredLanguages = preferredLanguages || [
			"en",
			"en-US",
			"pt",
			"pt-BR",
		]
	}

	async initialize(): Promise<void> {
		if (this.initialized) return
		this.initialized = true
	}

	async healthCheck(): Promise<boolean> {
		try {
			const testVideoId = "dQw4w9WgXcQ"
			const metadata = await this.extractMetadata(testVideoId)
			return !!metadata.title
		} catch {
			return false
		}
	}

	async cleanup(): Promise<void> {
		// No resources to clean up
	}

	// ========================================================================
	// DocumentExtractor Interface
	// ========================================================================

	/**
	 * Extract content from the given input
	 */
	async extract(input: ExtractionInput): Promise<ExtractionResult> {
		if (!input.url) {
			throw new Error("URL is required for YouTube extraction")
		}

		const videoId = this.parseVideoId(input.url)
		if (!videoId) {
			throw new Error("Invalid YouTube URL")
		}

		return await this.extractTranscript(videoId, {
			preferredLanguages: this.preferredLanguages,
			includeAutoGenerated: true,
			includeTimestamps: false,
		})
	}

	/**
	 * Check if this extractor can handle the given input
	 */
	canHandle(input: ExtractionInput): boolean {
		if (!input.url) return false
		return this.isYouTubeUrl(input.url)
	}

	/**
	 * Get extractor priority (higher = preferred)
	 */
	getPriority(): number {
		return 15 // High priority for YouTube URLs
	}

	/**
	 * Validate input before extraction
	 */
	async validateInput(input: ExtractionInput): Promise<void> {
		if (!input.url) {
			throw new Error("URL is required")
		}

		if (!this.isYouTubeUrl(input.url)) {
			throw new Error("Not a valid YouTube URL")
		}
	}

	// ========================================================================
	// YouTubeExtractor Interface
	// ========================================================================

	/**
	 * Extract transcript from YouTube video
	 */
	async extractTranscript(
		videoId: string,
		options?: YouTubeOptions,
	): Promise<ExtractionResult> {
		try {
			console.info("Extracting YouTube transcript", videoId)

			// First, try to get metadata
			const metadata = await this.extractMetadata(videoId)

			// Try to get transcript
			let transcript: string | null = null
			let transcriptSource = "none"

			try {
				transcript = await this.getTranscript(videoId, options)
				transcriptSource = "transcript"
			} catch (error) {
				console.warn(
					"Failed to get transcript, falling back to metadata only",
					videoId,
					(error as Error).message,
				)
			}

			// Fallback to metadata if no content
			const content = transcript || this.formatMetadataAsContent(metadata)

			const cleanedContent = this.cleanContent(content)

			return {
				text: cleanedContent,
				title: metadata.title,
				source: "youtube",
				url: `https://www.youtube.com/watch?v=${videoId}`,
				contentType: "video/youtube",
				raw: {
					metadata,
					videoId,
					transcriptSource,
				},
				wordCount: this.countWords(cleanedContent),
				extractorUsed: "YouTubeExtractor",
				extractionMetadata: {
					videoId,
					channelName: metadata.channelName,
					duration: metadata.duration,
					viewCount: metadata.viewCount,
					uploadDate: metadata.uploadDate,
					availableLanguages: metadata.availableLanguages,
					thumbnailUrl: metadata.thumbnailUrl,
				},
			}
		} catch (error) {
			throw error instanceof Error ? error : new Error(String(error))
		}
	}

	/**
	 * Extract metadata from YouTube video
	 */
	async extractMetadata(videoId: string): Promise<YouTubeMetadata> {
		console.debug("Extracting YouTube metadata", videoId)

		try {
			const result = await fetchYouTubeTranscriptFallback(
				`https://www.youtube.com/watch?v=${videoId}`,
				{ skipPythonFallback: true },
			)

			// Try to get title from metadata first (now extracted from page HTML)
			let title = result?.metadata?.title

			// Fallback: parse the result to extract title from markdown
			if (!title) {
				const markdown = result?.markdown || ""
				const lines = markdown.split("\n")
				title = lines[0]?.replace(/^#\s*/i, "") || undefined
			}

			// Second fallback: use oEmbed API
			if (!title || title === "Unknown") {
				console.debug("Trying oEmbed fallback for title", videoId)
				const oEmbedTitle = await fetchTitleFromOEmbed(videoId)
				if (oEmbedTitle) {
					title = oEmbedTitle
					console.info("Got title from oEmbed", videoId, title)
				}
			}

			// Final fallback
			if (!title) {
				title = `YouTube Video ${videoId}`
			}

			return {
				videoId,
				title,
				channelName: "Unknown",
				description: "",
				duration: 0,
				availableLanguages: this.preferredLanguages,
				thumbnailUrl: `https://img.youtube.com/vi/${videoId}/maxresdefault.jpg`,
			}
		} catch (error) {
			console.warn("Failed to extract metadata, trying oEmbed", videoId, (error as Error).message)

			// Try oEmbed as fallback
			const oEmbedTitle = await fetchTitleFromOEmbed(videoId)

			// Return minimal metadata with oEmbed title if available
			return {
				videoId,
				title: oEmbedTitle || `YouTube Video ${videoId}`,
				channelName: "Unknown",
				description: "",
				duration: 0,
				availableLanguages: [],
				thumbnailUrl: `https://img.youtube.com/vi/${videoId}/maxresdefault.jpg`,
			}
		}
	}

	/**
	 * Parse YouTube URL to get video ID
	 */
	parseVideoId(url: string): string | null {
		// Handle various YouTube URL formats
		const patterns = [
			/(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/)([a-zA-Z0-9_-]{11})/,
			/youtube\.com\/v\/([a-zA-Z0-9_-]{11})/,
			/youtube\.com\/shorts\/([a-zA-Z0-9_-]{11})/,
		]

		for (const pattern of patterns) {
			const match = url.match(pattern)
			if (match) return match[1]
		}

		// Check if it's just a video ID
		if (/^[a-zA-Z0-9_-]{11}$/.test(url)) {
			return url
		}

		return null
	}

	/**
	 * Check if URL is a valid YouTube URL
	 */
	isYouTubeUrl(url: string): boolean {
		const lowerUrl = url.toLowerCase()
		return (
			lowerUrl.includes("youtube.com") ||
			lowerUrl.includes("youtu.be") ||
			!!this.parseVideoId(url)
		)
	}

	// ========================================================================
	// Private Methods
	// ========================================================================

	/**
	 * Get transcript for video
	 */
	private async getTranscript(
		videoId: string,
		options?: YouTubeOptions,
	): Promise<string | null> {
		const videoUrl = `https://www.youtube.com/watch?v=${videoId}`

		try {
			let result = await fetchYouTubeTranscriptFallback(videoUrl)
			if (!result) {
				await new Promise((r) => setTimeout(r, 500))
				result = await fetchYouTubeTranscriptFallback(videoUrl)
			}

			if (!result) {
				return null
			}

			// Validate transcript length
			const markdown = result.markdown || ""
			const minLength = options?.minLength ?? 100
			if (markdown.length < minLength) {
				console.warn("Transcript too short", videoId, `length=${markdown.length}`, `minLength=${minLength}`)
				return null
			}

			return markdown
		} catch (error) {
			console.warn("Failed to fetch transcript", videoId, (error as Error).message)
			return null
		}
	}

	/**
	 * Format metadata as readable content (fallback)
	 */
	private formatMetadataAsContent(metadata: YouTubeMetadata): string {
		const parts: string[] = []

		parts.push(`Title: ${metadata.title}`)

		if (metadata.channelName) {
			parts.push(`Channel: ${metadata.channelName}`)
		}

		if (metadata.description) {
			parts.push(`\nDescription:\n${metadata.description}`)
		}

		if (metadata.duration > 0) {
			const minutes = Math.floor(metadata.duration / 60)
			const seconds = metadata.duration % 60
			parts.push(
				`\nDuration: ${minutes}:${seconds.toString().padStart(2, "0")}`,
			)
		}

		if (metadata.viewCount) {
			parts.push(`Views: ${metadata.viewCount.toLocaleString()}`)
		}

		if (metadata.uploadDate) {
			parts.push(`Uploaded: ${metadata.uploadDate.toLocaleDateString()}`)
		}

		return parts.join("\n")
	}

	/**
	 * Clean extracted content
	 */
	private cleanContent(content: string): string {
		let cleaned = content.replace(/\0/g, "")
		cleaned = cleaned.replace(/\s+/g, " ")
		cleaned = cleaned.replace(/\n{3,}/g, "\n\n")
		cleaned = cleaned.trim()
		return cleaned
	}

	/**
	 * Count words in text
	 */
	private countWords(text: string): number {
		const normalized = text.trim()
		if (!normalized) return 0
		return normalized.split(/\s+/).length
	}
}
